//
//  TopHeadlinesInteractor.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/11/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopHeadlinesBusinessLogic {
    func fetchTopHeadlines(request: Articles.FetchArticles.Request)
}

protocol TopHeadlinesDataStore {
    //var name: String { get set }
}

class TopHeadlinesInteractor: TopHeadlinesBusinessLogic, TopHeadlinesDataStore {
    var presenter: TopHeadlinesPresentationLogic?
    var worker: ArticlesWorker?
  
    // MARK: Do something
  
    func fetchTopHeadlines(request: Articles.FetchArticles.Request) {
        worker = ArticlesWorker()
        worker?.fetchArticles(with: request, completionHandler: { (response) in
            self.presenter?.presentTopHeadlines(response: response)
        })
    }
}
