//
//  TopHeadlinesPresenter.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/11/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopHeadlinesPresentationLogic
{
  func presentSomething(response: TopHeadlines.Something.Response)
}

class TopHeadlinesPresenter: TopHeadlinesPresentationLogic
{
  weak var viewController: TopHeadlinesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TopHeadlines.Something.Response)
  {
    let viewModel = TopHeadlines.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
