//
//  TopHeadlinesInteractor.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/11/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopHeadlinesBusinessLogic {
    func fetchTopHeadlines(request: TopHeadlines.FetchTopHeadlines.Request)
}

protocol TopHeadlinesDataStore {
    //var name: String { get set }
}

class TopHeadlinesInteractor: TopHeadlinesBusinessLogic, TopHeadlinesDataStore {
    var presenter: TopHeadlinesPresentationLogic?
    var worker: TopHeadlinesWorker?
  
    // MARK: Do something
  
    func fetchTopHeadlines(request: TopHeadlines.FetchTopHeadlines.Request) {
        worker = TopHeadlinesWorker()
        worker?.fetchTopHeadlines(with: request, completionHandler: { (articleList) in
            let response = TopHeadlines.FetchTopHeadlines.Response(articles: articleList?.articles, totalResults: articleList?.totalResults)
            self.presenter?.presentTopHeadlines(response: response)
        })
    }
}
