//
//  TopHeadlinesInteractor.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/11/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopHeadlinesBusinessLogic
{
  func doSomething(request: TopHeadlines.Something.Request)
}

protocol TopHeadlinesDataStore
{
  //var name: String { get set }
}

class TopHeadlinesInteractor: TopHeadlinesBusinessLogic, TopHeadlinesDataStore
{
  var presenter: TopHeadlinesPresentationLogic?
  var worker: TopHeadlinesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TopHeadlines.Something.Request)
  {
    worker = TopHeadlinesWorker()
    worker?.doSomeWork()
    
    let response = TopHeadlines.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
