//
//  ArticleDetailsPresenter.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/12/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleDetailsPresentationLogic
{
  func presentSomething(response: ArticleDetails.Something.Response)
}

class ArticleDetailsPresenter: ArticleDetailsPresentationLogic
{
  weak var viewController: ArticleDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ArticleDetails.Something.Response)
  {
    let viewModel = ArticleDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
