//
//  SavedArticlesPresenter.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SavedArticlesPresentationLogic
{
  func presentSomething(response: SavedArticles.Something.Response)
}

class SavedArticlesPresenter: SavedArticlesPresentationLogic
{
  weak var viewController: SavedArticlesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SavedArticles.Something.Response)
  {
    let viewModel = SavedArticles.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
