//
//  SavedArticlesInteractor.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SavedArticlesBusinessLogic
{
  func doSomething(request: SavedArticles.Something.Request)
}

protocol SavedArticlesDataStore
{
  //var name: String { get set }
}

class SavedArticlesInteractor: SavedArticlesBusinessLogic, SavedArticlesDataStore
{
  var presenter: SavedArticlesPresentationLogic?
  var worker: SavedArticlesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SavedArticles.Something.Request)
  {
    worker = SavedArticlesWorker()
    worker?.doSomeWork()
    
    let response = SavedArticles.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
