//
//  EverythingViewController.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EverythingDisplayLogic: class {
    func displayEverything(viewModel: Articles.FetchArticles.ViewModel)
}

class EverythingViewController: PagingTableViewController, EverythingDisplayLogic {
    var interactor: EverythingBusinessLogic?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = EverythingInteractor()
        let presenter = EverythingPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        launchFetchingData()
    }
    
    func launchFetchingData() {
        isLoading = true
        fetchArticles()
    }
    
    // MARK: Fetch Top Headlines
    
    override func fetchArticles(of page: Int = 1, with pageSize: Int = 15) {
        let request = Articles.FetchArticles.Request(url: API.Everything.url, params: API.Everything.params, page: page, pageSize: pageSize)
        interactor?.fetchEverything(request: request)
    }
    
    func displayEverything(viewModel: Articles.FetchArticles.ViewModel) {
        updateArticleList(articleList: viewModel.headlines ?? [], currentPage: viewModel.currentPage, resultsAmount: viewModel.totalResults)
    }
}
