//
//  EverythingInteractor.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EverythingBusinessLogic
{
  func doSomething(request: Everything.Something.Request)
}

protocol EverythingDataStore
{
  //var name: String { get set }
}

class EverythingInteractor: EverythingBusinessLogic, EverythingDataStore
{
  var presenter: EverythingPresentationLogic?
  var worker: EverythingWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Everything.Something.Request)
  {
    worker = EverythingWorker()
    worker?.doSomeWork()
    
    let response = Everything.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
