//
//  EverythingPresenter.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EverythingPresentationLogic {
    func presentEverything(response: Articles.FetchArticles.Response?)
}

class EverythingPresenter: EverythingPresentationLogic {
    weak var viewController: EverythingDisplayLogic?
    var worker = ArticlesWorker()
    
    // MARK: Present Everything
    
    func presentEverything(response: Articles.FetchArticles.Response?) {
        let viewModel = worker.createArticlesViewModel(with: response)
        viewController?.displayEverything(viewModel: viewModel)
    }
}
