//
//  EverythingPresenter.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EverythingPresentationLogic
{
  func presentSomething(response: Everything.Something.Response)
}

class EverythingPresenter: EverythingPresentationLogic
{
  weak var viewController: EverythingDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Everything.Something.Response)
  {
    let viewModel = Everything.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
