//
//  EverythingInteractor.swift
//  ScienceNews
//
//  Created by Dinara Shadyarova on 1/13/20.
//  Copyright (c) 2020 Dinara Shadyarova. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EverythingBusinessLogic
{
  func fetchEverything(request: Articles.FetchArticles.Request)
}

protocol EverythingDataStore
{
  //var name: String { get set }
}

class EverythingInteractor: EverythingBusinessLogic, EverythingDataStore
{
    var presenter: EverythingPresentationLogic?
    var worker: ArticlesWorker?
    
    // MARK: Do something
    
    func fetchEverything(request: Articles.FetchArticles.Request) {
        worker = ArticlesWorker()
        worker?.fetchArticles(with: request, completionHandler: { (response) in
            self.presenter?.presentEverything(response: response)
        })
    }
}

